In [1]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8)

In [2]:
db.shape

torch.Size([5000])

In [0]:
remove_index = 2

In [3]:
db[0:2]

tensor([0, 1], dtype=torch.uint8)

In [4]:
db[3:]

tensor([0, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [7]:
torch.cat((db[0:2],db[3:]))

tensor([0, 1, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [8]:
torch.cat((db[0:2],db[3:]))[0:5]

tensor([0, 1, 0, 0, 0], dtype=torch.uint8)

In [0]:
def get_parallel_db(db, remove_index):
  
  return torch.cat((db[0:remove_index],db[remove_index + 1:]))

In [10]:
get_parallel_db(db, 3)

tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8)

In [11]:
get_parallel_db(db, 3)[0:5]

tensor([0, 1, 1, 0, 0], dtype=torch.uint8)

In [13]:
get_parallel_db(db, 0).shape

torch.Size([4999])

In [14]:
get_parallel_db(db, 52352).shape

torch.Size([5000])

In [0]:
parallel_dbs = list()

In [0]:
for i in range(len(db)):
  pdb = get_parallel_db(db, i)
  parallel_dbs.append(pdb)

In [17]:
len(parallel_dbs)

5000

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [20]:
pdbs

[tensor([1, 1, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 1, 0

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [23]:
db

tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       dtype=torch.uint8)

In [24]:
pdbs

[tensor([1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,