In [0]:
import torch

In [0]:
def get_parallel_db(db, remove_index):
  
  return torch.cat((db[0:remove_index],db[remove_index + 1:]))

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [18]:
db

tensor([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
       dtype=torch.uint8)

In [19]:
pdbs

[tensor([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,

In [0]:
def query(db):
  
  return db.sum()

In [21]:
query(db)

tensor(8)

In [24]:
query(pdbs[3])

tensor(8)

In [0]:
full_db_result = query(db)

In [0]:
max_distance = 0
for pdb in pdbs:
  pdb_result = query(pdb)
  
  db_distance = torch.abs(pdb_result - full_db_result)
  
  if(db_distance > max_distance):
    max_distance = db_distance

In [0]:
def sensitivity(query, n_entries=1000):
  
  db, pdbs = create_db_and_parallels(n_entries)
  full_db_result = query(db)
  
  max_distance = 0
  for pdb in pdbs:
    pdb_result = query(pdb)

    db_distance = torch.abs(pdb_result - full_db_result)

    if(db_distance > max_distance):
      max_distance = db_distance
      
  return max_distance

In [31]:
sensitivity(query)

tensor(1)

In [0]:
def query(db):
  
  return db.float().mean()

In [33]:
sensitivity(query)

tensor(0.0005)